### ISSUE TITLE
make失败，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [heiher/hev-dns-forwarder#1]
hi.

yudeMacBook-Air:hev-dns-forwarder brite$ make
clang: error: no such file or directory: 'c'
clang: error: no such file or directory: '../hev-lib/include'
clang: error: no input files
clang: error: no such file or directory: 'c'
clang: error: no such file or directory: '../hev-lib/include'
clang: error: no input files
clang: error: no such file or directory: 'c'
clang: error: no such file or directory: '../hev-lib/include'
clang: error: no input files
clang: error: no such file or directory: 'c'
clang: error: no such file or directory: '../hev-lib/include'
clang: error: no input files
-n Building src/hev-dns-forwarder.c ... 
src/hev-dns-forwarder.c:15:10: fatal error: 'sys/epoll.h' file not found
# include <sys/epoll.h>

```
     ^
```

1 error generated.
make: **\* [build/hev-dns-forwarder.o] Error 1
yudeMacBook-Air:hev-dns-forwarder brite$

**Comment by luckypoem** [comment]
看到这里https://github.com/williame/hellepoll/issues/2 说：“port it to use kqueue, which OSX does support.”，怎么port呢？

**Comment by heiher** [comment]
不支持 mac os。
