### ISSUE TITLE
能自定义非标准53端口吗？

### ISSUE THREAD

**Issue by ekenchan** [heiher/hev-dns-forwarder#2]
RT

**Comment by heiher** [comment]
目前不支持参数控制，代码中是固定的 upstream 端口，不过你可以改 :)：https://github.com/heiher/hev-dns-forwarder/blob/master/src/hev-dns-forwarder.c#L94

**Comment by ekenchan** [comment]
谢谢，已改成参数控制

![_20161017103011](https://cloud.githubusercontent.com/assets/2436300/19423625/d619c9e8-9454-11e6-85ac-998c88403f4c.png)
